version: '3.8'

services:

  # Node.js runtime
  app:
    build:
      context: .
    container_name: app-container
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    networks:
      - custom-network
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    restart: always
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    build:
      context: ./database
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom-network
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    restart: always

networks:
  custom-network:
    driver: bridge

volumes:
  node_modules:
  postgres-db:
  postgres-logs: